#!/bin/bash
#-------------------------------------------------------------------------------
#                                                                     2022-02-22
                                                                  Version="1.01"
#  Installatore costruito dopo quickstart
#
#  scopo:
#    Inizializzazione scheda raspi con
#      OS base raspbian
#      estensione firstboot da raspberian
#        <-- credits to:   ?fare link
#      estensione script server da bugy/script server
#        <-- credits to:   ?fare link
#
#   https://github.com/fpirri/gothings-raspi-install/raw/master/raspiinit
#-------------------------------------------------------------------------------
#
# download:
#   wget -O ./raspiinit https://github.com/fpirri/gothings-install/raw/master/raspiinit
#
#-------------------------------------------------------------------------------
#
# creazione archivio:
#   sudo tar -czvpf "${NameArchive}" dockrepo/
#     <-- in questo caso puo' bastare: dockrepo/sysdata
#
#------------------------------------------------------------------------------
#                                                                         avviso
echo
echo "=============================================================== $Version"
echo
echo "    GOTHINGS boot loader for Raspberry (C) board management"
echo
echo "======================================================================="
echo
echo 'This script will download software from github
The board will be able to run initialization software at next boot
This allows you to use a standard browser to access the board

The script creates a directory in your homedir, named "dockrepo", to contain the
installer and future downloads of GoThings software

Please look at the README file on github to verify the performed operations
  ( https://github.com/fpirri/gothings-install/ )

You can find information on Gothings software at: www.gothings.org
'
#
################################################################################
#                                          download latest manager da repository
#
# per evitare la cache (nel network) durante lo sviluppo:
# wget --no-check-certificate --no-cache --no-cookies -O ./raspiinit https://github.com/fpirri/gothings-install/raw/master/raspiinit
#
wget -O ./quickinstall.tar.gz https://github.com/fpirri/gothings-raspi-install/raw/master/quickinstall.tar.gz
Result=$?
if [ $Result -gt 0 ]
then
  echo "Error $Result while reading quickinstall.tar.gz on github"
  echo "This should not happen!"
  echo "please verify your internet connection"
  echo "Eventually, please report to the developers"
  exit
fi
################################################################################
#                                                             expand in dockrepo
#
sudo tar xpf quickinstall.tar.gz -C "${HOME}"
Result=$?
if [ $Result -gt 0 ]
then
  echo "Error $Result while expanding the quickinstall.tar.gz archive"
  echo "This should not happen!"
  echo "Eventually, please report to the developers"
fi
#
#
################################################################################
#                                                                installa sul PC
#
cd ~/dockrepo/sysdata/raspi-install
Return=$?
if [ $Result -gt 0 ]
then
  echo "Error $Result while changing directory to ~/dockrepo/sysdata/raspi-install"
  echo "This should not happen!"
  echo "Eventually, please report to the developers"
fi
bash /dockrepo/raspi-install/quickstart.sh
Return=$?
if [ $Result -gt 0 ]
then
  echo "Error $Result while executing quickstart"
  echo "This may happen from errors during quickstart execution"
  echo "Please report all errors you find to the developers"
fi
#
################################################################################
#                                                                Avvisa l'utente
#
echo
echo "No errors?"
echo
echo "Congratulations! You have installed firstboot service into your board"
echo
echo "You may continue to reboot your board and invoke firstboot"
echo "After that you can access the board from your browser at:"
echo "  localhost:5000"
echo
echo
