#!/bin/bash
#                                                                    2022-01-09
                                                                 VERSION="02.00"
#
#   Set raspbian boot dir
#     --> set initial data for raspbian system bootstrap
#     --> enable ssh
#     --> set wifi credential
#     --> load run_once.sh & run_once.tar.gz
#
# ref.:
#    Linux:  https://styxit.com/2017/03/14/headless-raspberry-setup.html
#  Windows:  https://desertbot.io/blog/headless-pi-zero-w-wifi-setup-windows
#
################################################################################
#                                                  how to get & exec this script
#   mkdir temp    <-- any temporary directory is OK
#   cd temp
#   wget -q -O setsdcard - https://github.com/fpirri/gothings-raspi-install/raw/master/setsdcard
#   **** VERIFICA lo script ***
#   bash ./setsdcard
#     <-- SEGUI le istruzioni ...
#
################################################################################
#  In aggiornamento:
#    - uso di run_once
#    - script iniziale: run_once.sh
#
##############
#  DA FARE:
#  - aggiungere: scopri ??/boot & verifica che sia raspbian
#  - verifica che ci siano i file richiesti:  WpaConfFile etc.
#  - chiedi & accetta wifi ssid & pass phrase
#      <-- 
#  - controlla validita' di tutte le scritture ...
#  - verificare aggiornamenti
#
################################################################################
#                                                                      variables
#generic
Editor=nano
Red='\033[0;41;30m'
Std='\033[0;0;39m'
# --- boot volume path:
SdBootDir="/media/$USER/boot/"
#
# --- wi-fi configuration
Data1='ap_scan=1
update_config=1
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
network={
    ssid="'
Data2='
    psk="'
Data3='
}'
#Data3='
#    key_mgmt=WPA-PSK
#}
#network={
#    ssid="another ssid you may use"
#    psk="password for another wifi network"
#    key_mgmt=WPA-PSK
#}'
#
################################################################################
#
pause(){
#  continue or exit
  echo "--------------------------------------------------------------/"
  read -rsp $'Press any key to continue or ^C to exit ...' -n 1 key
}
#
################################################################################
#                                                                           MAIN
echo
echo "======================================================= version $VERSION"
echo
echo "This script will download data from:"
echo "   https://github.com/fpirri/gothings-raspi-install/"
echo
echo -e "${Red} Please be sure to verify security at least the first time ! ${Std}"
echo
pause
echo
echo "Verify sd card presence"
if [ ! -s "${SdBootDir}" ]
then
  echo -e "${Red} Sorry, I can't find the sd card boot device: ${SdBootDir} ${Std}"
  echo "I stop processing NOW"
  echo
  echo "Please mount your sdcard at the location: ${SdBootDir}"
  echo "It may suffice to extract and re-insert the sdcard"
  echo
  exit
fi
echo
echo "Download files:"
# file di inzializzazione
FirstBootFile="firstboot.sh"
echo "${FirstBootFile}"
wget -q -O "${FirstBootFile}" https://github.com/fpirri/gothings-raspi-install/raw/master/"${FirstBootFile}"
RunOnceArchive="run_once.tar.gz"
echo "${RunOnceArchive}"
wget -q -O "${RunOnceArchive}" https://github.com/fpirri/gothings-raspi-install/raw/master/"${RunOnceArchive}"
RunOnceScript="run_once.sh"
echo "${RunOnceScript}"
wget -q -O "${RunOnceScript}" https://github.com/fpirri/gothings-raspi-install/raw/master/"${RunOnceScript}"
echo
echo "Initialization files downloaded"
echo
echo "verify wifi credentials ..."
# file di configurazione, verra' usato come 'source' di SSID & PSK
WpaConfFile="WpaConfFile"
if [ ! -s "${WpaConfFile}" ]
then
  echo
  echo "wifi credentials definition file template does not exits"
  echo "Let'get ${WpaConfFile}"
  wget -q -O "${WpaConfFile}" - https://github.com/fpirri/gothings-raspi-install/raw/master/"${WpaConfFile}"
  echo
  echo "Please edit ${WpaConfFile} file to contain your wifi SSID and PSK,"
  echo "then re-execute this script with 'bash setsdcard' at the prompt"
  exit
  ################## FINE
else
  source WpaConfFile
  WpaData=$(printf "${Data1}${RaspiSsid}\"${Data2}${RaspiPsk}\"${Data3}")
  echo
  echo "Your wifi credentials are:"
  echo -e ${WpaData}
  echo "Please exit and retry if credentials are not correct"
  pause
fi  

#  cp ~/NetBeansProjects/github-gothings/gothings-raspi-install/setsdcard ./
# --- wi-fi credentials:
#
echo
echo "======================================================= version $VERSION"
echo
echo "All data are now available"
echo "This script will now write data on: ${SdBootDir}"
echo
##    ... chiedi conferma prima di proseguire
pause

echo
touch "${SdBootDir}ssh"
echo "SSH Enabled"

WpaFile="${SdBootDir}wpa_supplicant.conf"
echo "${WpaData}" > ${WpaFile}
echo "WiFi configuration written"

echo "Copy firstboot.sh & make it executable"
cp firstboot.sh "${SdBootDir}firstboot.sh"
chmod +x "${SdBootDir}firstboot.sh"
echo "firstboot.sh OK"

echo "Copy run_once.tar.gz archive"
cp  run_once.tar.gz "${SdBootDir}run_once.tar.gz"
echo "Run_once archive OK"

echo "Copy run_once.sh script"
cp run_once.sh "${SdBootDir}run_once.sh"
echo "run_once.sh script OK"

echo
echo "Set 'boot' partition OK"
echo "FINE"
