#!/bin/bash
#                                                                    2022-01-09
                                                                 VERSION="02.00"
#
#   Set raspbian boot dir
#     --> set initial data for raspbian system bootstrap
#     --> enable ssh
#     --> set wifi credential
#     --> load run_once.sh & run_once.tar.gz
#
# ref.:
#    Linux:  https://styxit.com/2017/03/14/headless-raspberry-setup.html
#  Windows:  https://desertbot.io/blog/headless-pi-zero-w-wifi-setup-windows
#
################################################################################
#  In aggiornamento:
#    - uso di run_once
#    - script iniziale: run_once.sh
#
##############
#  DA FARE:
#  - aggiungere: scopri ??/boot & verifica che sia raspbian
#  - verifica che ci siano i file richiesti:  WpaConfFile etc.
#  - chiedi & accetta wifi ssid & pass phrase
#      <-- 
#  - controlla validita' di tutte le scritture ...
#  - verificare aggiornamenti
#
################################################################################
#                                                                      variables
#generic
Editor=nano
Red='\033[0;41;30m'
Std='\033[0;0;39m'
# --- boot volume path:
SdBootDir="/media/$USER/boot/"
#
# --- wi-fi configuration
Data1='ap_scan=1
update_config=1
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
network={
    ssid="'
Data2='
    psk="'
Data3='
    key_mgmt=WPA-PSK
}
network={
    ssid="another ssid you may use"
    psk="password for another wifi network"
    key_mgmt=WPA-PSK
}'
#
################################################################################
#

pause(){
#  continue or exit
  echo "--------------------------------------------------------------/"
  read -rsp $'Press any key to continue or ^C to exit ...' -n 1 key
}

echo
echo "======================================================= version $VERSION"
echo
echo "This script will download data from:"
echo "   https://github.com/fpirri/gothings-raspi-install/"
echo
echo -e "${Red} Please be sure to verify security at least the first time ! ${Std}"
echo
pause
echo
echo "Download files:"
# file di inzializzazione
FirstBootFile="firstboot.sh"
echo "${FirstBootFile}"
wget -nv -O "${FirstBootFile}" https://github.com/fpirri/gothings-raspi-install/raw/master/"${FirstBootFile}"
RunOnceArchive="run_once.tar.gz"
echo "${RunOnceArchive}"
wget -nv -O "${RunOnceArchive}" https://github.com/fpirri/gothings-raspi-install/raw/master/"${RunOnceArchive}"
RunOnceScript="run_once.sh"
echo "${RunOnceScript}"
wget -nv -O "${RunOnceScript}" https://github.com/fpirri/gothings-raspi-install/raw/master/"${RunOnceScript}"
echo
echo "Initialization files downloded"
echo "verify wifi credentials ..."
pause
# file di configurazione
WpaConfFile="WpaConfFile"
if [ ! -s "${WpaConfFile}" ]
then
  echo"Get wifi credentials definition file template"
  wget -O "${WpaConfFile}" - https://github.com/fpirri/gothings-raspi-install/raw/master/"${WpaConfFile}"
  echo "Please edit ${WpaConfFile} file to contain your wifi SSID and PSK,"
  echo "then re-execute this script with 'bash setsdcard' at the prompt"
  exit
  ################## FINE
else
  source WpaConfFile
  WpaData=$(printf "${Data1}${RaspiSsid}\"${Data2}${RaspiPsk}\"${Data3}")
  echo "Your wifi credentials are:"
  echo -e ${WpaData}
  echo "FARE VERIFICA"
  pause
  exit
fi  



WpaData=$(printf "${Data1}${RaspiSsid}\"${Data2}${RaspiPsk}\"${Data3}")
echo "File delle credenziali wi-fi:"
echo -e ${WpaData}

echo "WiFi credentials ..."
# --- wi-fi credentials:

echo "Qui dovremmo controllare le credenziali wi-fi"
exit
pause

echo
echo "
echo "======================================================= version $VERSION"
echo
echo "This script will write data on: ${SdBootDir}"
echo
##    ... chiedi conferma prima di proseguire
pause

touch "${SdBootDir}ssh"
echo "SSH Enabled"

WpaFile="${SdBootDir}wpa_supplicant.conf"
echo "${WpaData}" > ${WpaFile}
echo "WiFi configuration written"

echo "Copy firstboot.sh & make it executable"
cp firstboot.sh "${SdBootDir}firstboot.sh"
chmod +x "${SdBootDir}firstboot.sh"
echo "firstboot.sh OK"

echo "Copy run_once.tar.gz archive"
cp  "${SdBootDir}run_once.tar.gz"
echo "Run_once archive OK"

echo "Copy run_once.sh script"
cp run_once.sh "${SdBootDir}run_once.sh"
echo "run_once.sh script OK"

echo
echo "Set 'boot' partition OK"
echo "FINE"
